# Compiler and flags
CORE ?= 8


# Paths
platform=gvsoc
BUILD_DIR = ./
SRC_DIR = ./src
# Output file name
TARGET = match_app
# Include paths
STANDALONE_CRT_PATH := $(abspath $(BUILD_DIR))/runtime
CODEGEN_PATH := $(abspath $(BUILD_DIR))/codegen
MODEL_DIRS := $(wildcard $(CODEGEN_PATH)/*)
MODELS = $(wildcard $(abspath $(BUILD_DIR))/codegen/*)
INC_PATHS = -I${STANDALONE_CRT_PATH}/include \
			 -I${STANDALONE_CRT_PATH}/src/runtime/crt/include \
			 $(foreach model, $(MODEL_DIRS), -I$(model)/include) \
			 -I ./include/

# Source files
SRC =  $(foreach model, $(MODEL_DIRS), $(wildcard $(model)/src/*.c)) $(shell find $(abspath $(SRC_DIR)) -name '*.c')  $(STANDALONE_CRT_PATH)/src/runtime/crt/common/crt_backend_api.c $(STANDALONE_CRT_PATH)/src/runtime/crt/memory/stack_allocator.c


# Defining the source files for pulp-runtime
APP = match_app
APP_SRCS = $(SRC)
PULP_INC_PATHS += -DSDK

# Note that this value can automatically be changed by python scripts:
OPT_LEVEL = 3
# Use -DNDEBUG to remove assertions in TVM runtime
# Use -DPULP for preprocessor in malloc wrapper
# Need to link in libm for math.h inclusion in softmax operator
APP_CFLAGS += -DNUM_CORES=$(CORE) -g $(INC_PATHS) -DNDEBUG -O$(OPT_LEVEL) -DPULP 
# GAP9 fixes, the first because abort() is not in stdlib. The second to avoid a crt_backend_api.c error
APP_CFLAGS +=  -Wno-error=format -w -fno-indirect-inlining -w #-flto
APP_LDFLAGS += -lm -Wl,--print-memory-usage #-flto

GAP9_DEFAULT_FLASH_TYPE = DEFAULT_FLASH
GAP9_DEFAULT_RAM_TYPE = DEFAULT_RAM

GAP8_DEFAULT_FLASH_TYPE = HYPERFLASH
GAP8_DEFAULT_RAM_TYPE = HYPERRAM

PULP_DEFAULT_FLASH_TYPE = HYPERFLASH
PULP_DEFAULT_RAM_TYPE = HYPERRAM

FLASH_TYPE ?= $($(TARGET_CHIP_FAMILY)_DEFAULT_FLASH_TYPE)
RAM_TYPE ?= $($(TARGET_CHIP_FAMILY)_DEFAULT_RAM_TYPE)

ifeq '$(FLASH_TYPE)' 'MRAM'
READFS_FLASH = target/chip/soc/mram
endif

APP_CFLAGS += -DFLASH_TYPE=$(FLASH_TYPE) -DUSE_$(FLASH_TYPE) -DUSE_$(RAM_TYPE)
APP_CFLAGS += -DSINGLE_CORE_DMA


APP_CFLAGS += -DPULP_SDK=1
APP_CFLAGS += -DTARGET_CHIP_FAMILY_$(TARGET_CHIP_FAMILY)

MODELS_PATHS := $(wildcard $(abspath $(BUILD_DIR))/models/*)
FLASH_FILES = $(foreach model, $(MODELS_PATHS), $(wildcard $(model)/parameters/*))

READFS_FILES := $(FLASH_FILES)
APP_CFLAGS += -DFS_READ_FS
################################### SPECIAL ####################################

# The special rule modifiers (.PHONY etc...) go here

#################################### RULES #####################################

include $(RULES_DIR)/pmsis_rules.mk

##################################### EOF ######################################
